django/mydiary/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    path('userdetail/<int:user_id>/', views.userdetail, name='userdetail'),
    path('userdetail/profile_modify/<int:user_id>/', views.profile_modify, name='profile_modify'),
    path('userdetail/profile_delete/<int:user_id>/', views.profile_delete, name='profile_delete'),
]


handler404 = 'common.views.page_not_found'

django/mydiary/main/urls.py
from django.urls import path
from .views import base_views, posts_views, reply_views


app_name = 'main'

urlpatterns = [
    path('<str:category>/', base_views.index, name='index'),
    path('detail/<int:posts_id>/', base_views.detail, name='detail'),
    
    path('posts/create/', posts_views.posts_create, name='posts_create'),
    path('posts/modify/<int:posts_id>/', posts_views.posts_modify, name='posts_modify'),
    path('posts/delete/<int:posts_id>/', posts_views.posts_delete, name='posts_delete'),
    path('posts/vote/<int:posts_id>/', posts_views.posts_vote, name='posts_vote'),

    path('reply/create/<int:posts_id>/', reply_views.reply_create, name='reply_create'),
    path('reply/modify/<int:reply_id>/', reply_views.reply_modify, name='reply_modify'),
    path('reply/delete/<int:reply_id>/', reply_views.reply_delete, name='reply_delete'),
    path('reply/vote/<int:reply_id>/', reply_views.reply_vote, name='reply_vote'),
]

django/mydiary/main/models.py
from django.db import models
from django.contrib.auth.models import User



class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    def __str__(self):
        return self.name


class Posts(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_posts')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_posts', null=True)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_posts')

    def __str__(self):
        return self.subject


class Reply(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_reply')
    posts = models.ForeignKey(Posts, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    # null=True : 데이터베이스에서 null을 허용, blanck=True : form_isvalid 에서 값이 없어도 검사를 통과를 허용
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_reply')

django/mydiary/main/forms.py
from django import forms
from main.models import Posts, Reply


class PostsForm(forms.ModelForm):
    class Meta:
        model = Posts  # 사용할 모델
        fields = ['category', 'subject', 'content']  # PostsForm에서 사용할 Posts 모델의 속성

        labels = {
            'category': '카테고리',
            'subject': '제목', # 필드명 보여줄때 지정가능
            'content': '내용',
        }


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['content']
        labels = {
            'content' : '댓글 내용'
        }

django/mydiary/main/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from ..models import Posts
from django.db.models import Q, Count



def index(request, category=None):
    page = request.GET.get('page', '1') # 페이지를 읽어온다. 없을경우 1을 뱉는다 ?page =
    kw = request.GET.get('kw', '') # 검색어

    if category == 'freeboard':
        posts_list = Posts.objects.filter(category_id=1).order_by('-create_date')
    elif category == 'diary':
        posts_list = Posts.objects.filter(category_id=2).order_by('-create_date')
    elif category == 'QnA':
        posts_list = Posts.objects.filter(category_id=3).order_by('-create_date')
    else:
        posts_list = Posts.objects.order_by('-create_date')

    if kw:
        posts_list = posts_list.filter( # icontains 대소문자 구분없음, 있음은 contains
            Q(subject__icontains=kw) | # 제목 검색
            Q(content__icontains=kw) | # 내용 검색
            Q(reply__content__icontains=kw) | # 댓글 내용
            Q(reply__author__username__icontains=kw) | # 댓글 작성자
            Q(author__username__icontains=kw) # 일기 작성자
        ).distinct() # 중복제거
    paginator = Paginator(posts_list, 10) # 한페이지에 보여줄 페이지 갯수 10
    page_obj = paginator.get_page(page) # 페이지 오브젝트에 담아서 보여줌
    context = {'category': category, 'posts_list': page_obj, 'page': page, 'kw': kw}

    return render(request, 'main/posts_list.html', context)


def detail(request, posts_id):
    posts = get_object_or_404(Posts, pk=posts_id)

    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', 'first') # 정렬방법

    if kw == 'voter': # 추천순
        paginator = Paginator(posts.reply_set.all().annotate(num_votes=Count('voter')).order_by('-num_votes'), 10)
    elif kw == 'latest': # 최신순
        paginator = Paginator(posts.reply_set.all().order_by('-id'), 10)
    else: # 등록순
        paginator = Paginator(posts.reply_set.all(), 10)

    page_obj = paginator.get_page(page)

    context = {'posts': posts, 'reply_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'main/posts_detail.html', context)

django/mydiary/main/views/posts_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from ..forms import PostsForm
from django.utils import timezone
from django.contrib import messages
from ..models import Posts



@login_required(login_url='common:login')
def posts_create(request):
    if request.method == 'POST': # POST 요청이면
        form = PostsForm(request.POST) # 다이어리폼에 요청내용을 담는다
        if form.is_valid(): # 폼이 유효한지 검사한다
            posts = form.save(commit=False) # 다이어리라는 변수에 임시저장
            posts.author = request.user # author 값에 로그인중인 유저정보를 담는다
            posts.create_date = timezone.now() # 현재시간 추가
            posts.save() # 최종 저장
            return redirect('/')
    else:
        form = PostsForm()
    context = {'form' : form}
    return render(request, 'main/posts_form.html', context)


@login_required(login_url='common:login')
def posts_modify(request, posts_id):
    posts = get_object_or_404(Posts, pk=posts_id)
    if request.user != posts.author:
        messages.error(request, '권한이 없습니다.')
        return redirect('main:detail', posts_id=posts.id)
    if request.method == 'POST':
        form = PostsForm(request.POST, instance=posts)
        if form.is_valid():
            posts = form.save(commit=False)
            posts.modify_date = timezone.now()
            posts.save()
            return redirect('main:detail', posts_id=posts.id)
    else:
        form = PostsForm(instance=posts)
    context = {'form': form}
    return render(request, 'main/posts_form.html', context)


@login_required(login_url='common:login')
def posts_delete(request, posts_id):
    posts = get_object_or_404(Posts, pk=posts_id)
    if request.user != posts.author:
        messages.error(request, '권한이 없습니다.')
        return redirect('main:detail', posts_id=posts.id)
    posts.delete()
    return redirect('index')


@login_required(login_url='common:login')
def posts_vote(request, posts_id):
    posts = get_object_or_404(Posts, pk=posts_id)
    if posts.voter.filter(id=request.user.id).exists():
        posts.voter.remove(request.user)
    else:
        posts.voter.add(request.user)
    return redirect('main:detail', posts_id=posts.id)

django/mydiary/main/views/reply_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from ..forms import ReplyForm
from ..models import Posts, Reply
from math import ceil # 소수점올림 -> 페이지 구하려고



@login_required(login_url='common:login')
def reply_create(request, posts_id):
    posts = get_object_or_404(Posts, pk=posts_id)
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.author = request.user
            reply.create_date = timezone.now()
            reply.posts = posts
            reply.save()
            # return redirect('{}?page=0#reply_{}'.format(resolve_url('main:detail', posts_id=posts.id), reply.id)) # 앵커 + ?page=-1 마지막페이지
            return redirect(resolve_url('main:detail', posts_id=posts.id) + '?page=0#reply_' + str(reply.id))
            # main/posts_id + ?page=0#reply_ + reply.id
            # 리졸브로 만든 주소와 받아온 댓글번호 사이에 포멧함수로 끼워넣음 -> 리디렉트
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'posts': posts, 'form': form}
    return render(request, 'main/posts_detail.html', context)


@login_required(login_url='common:login')
def reply_modify(request, reply_id):
    reply = get_object_or_404(Reply, pk=reply_id)
    if request.user != reply.author:
        messages.error(request, '권한이 없습니다.')
        return redirect('main:detail', posts_id=reply.posts.id)
    if request.method == 'POST':
        form = ReplyForm(request.POST, instance=reply)
        if form.is_valid():
            page = ceil((list(reply.posts.reply_set.all()).index(reply)+1)/10)
            reply = form.save(commit=False)
            reply.modify_date = timezone.now()
            reply.save()
            return redirect('{}?page={}#reply_{}'.format(
                resolve_url('main:detail', posts_id=reply.posts.id),
                page,
                reply.id
            ))
    else:
        form = ReplyForm(instance=reply)
    context = {'reply': reply, 'form': form}

    return render(request, 'main/reply_form.html', context)


@login_required(login_url='common:login')
def reply_delete(request, reply_id):
    reply = get_object_or_404(Reply, pk=reply_id)
    if request.user != reply.author:
        messages.error(request, '권한이 없습니다.')
    else:
        reply.delete()
    return redirect('main:detail', posts_id=reply.posts.id)


@login_required(login_url='common:login')
def reply_vote(request, reply_id):
    reply = get_object_or_404(Reply, pk=reply_id)
    page = ceil((list(reply.posts.reply_set.all()).index(reply)+1)/10)
    if reply.voter.filter(id=request.user.id).exists():
        reply.voter.remove(request.user)
    else:
        reply.voter.add(request.user)
    return redirect('{}?page={}#reply_{}'.format(
                resolve_url('main:detail', posts_id=reply.posts.id),
                page,
                reply.id
            ))

django/mydiary/templates/main/posts_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul>
            <li>{{ message.message }}</li>
        </ul>
        {% endfor %}
    </div>
    {% endif %}
    <!-- 일기 -->
    <h2 class="border-bottom py-2">{{ posts.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ posts.content }}</div>
            <div class="d-flex justify-content-end">
                {% if posts.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">수정됨</div>
                    <div>{{ posts.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2"><a href="{% url 'common:userdetail' posts.author.profile.user_id %}">{{ posts.author.username }}</a></div>
                    <div>{{ posts.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="{% url 'main:posts_vote' posts.id  %}" class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{ posts.voter.count }}</span>
                </a>
                {% if request.user == posts.author %}
                <a href="{% url 'main:posts_modify' posts.id  %}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" data-uri="{% url 'main:posts_delete' posts.id  %}"
                    class="delete btn btn-sm btn-outline-secondary">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- 댓글 -->

    <div class="col-4 d-flex align-items-center">
        <select id="sort_kind">
            <option value="first">등록순</option>
            <option value="latest">최신순</option>
            <option value="voter">추천순</option>
        </select>
        <button class="btn btn-sm btn-outline-secondary mx-1" type="button" id="btn_sort">정렬</button>
    </div>
    <h5 class="border-bottom my-3 py-2">{{posts.reply_set.count}}개의 댓글이 있습니다.</h5>

    {% for reply in reply_list %}
    <a id="reply_{{ reply.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ reply.content }}</div>
            <div class="d-flex justify-content-end">
                {% if reply.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">수정됨</div>
                    <div>{{ reply.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2"><a href="{% url 'common:userdetail' reply.author.profile.user_id %}">{{ reply.author.username }}</a></div>
                    <div>{{ reply.create_date }}</div>
                </div>
            </div>

            <div class="my-3">
                <a href="{% url 'main:reply_vote' reply.id %}" class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{ reply.voter.count }}</span>
                </a>
                {% if request.user == reply.author %}
                <a href="{% url 'main:reply_modify' reply.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" data-uri="{% url 'main:reply_delete' reply.id %}"
                    class="delete btn btn-sm btn-outline-secondary">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if reply_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ reply_list.previous_page_number }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in reply_list.paginator.page_range %}
        {% if page_number >= reply_list.number|add:-5 and reply_list.number|add:5 >= page_number %}
        {% if page_number == reply_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if reply_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ reply_list.next_page_number }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->

    <!-- 댓글 등록 -->
    <form action="{% url 'main:reply_create' posts.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">댓글내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %} name="content" id="content"
                class="form-control" rows="2"></textarea>
        </div>
        <input type="submit" value="댓글등록" class="btn btn-primary">
    </form>
</div>
<form id="sort_kind_form" method="get" action="{% url 'main:detail' posts.id %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
    // 댓글삭제
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function (element) {
        element.addEventListener('click', function () {
            if (confirm("정말로 삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });

    // 페이징 및 댓글정렬
    $('#sort_kind').val($('#kw').val()).prop("selected", true);

    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function (element) {
        element.addEventListener('click', function () {
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('sort_kind_form').submit();
        });
    });
    const btn_sort = document.getElementById("btn_sort");
    btn_sort.addEventListener('click', function () {
        document.getElementById('kw').value = document.getElementById('sort_kind').value;
        document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        document.getElementById('sort_kind_form').submit();
    });
</script>
{% endblock %}

django/mydiary/templates/main/posts_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">글쓰기</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% include "form_errors.html" %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="category" class="form-label">카테고리</label>
            <select name="category" class="form-control">
                <option value="0">---카테고리를 선택하세요---</option>
                <option value="1">자유게시판</option>
                <option value="2">일기장</option>
                <option value="3">Q&A</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content" id="content"
                rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

django/mydiary/templates/main/posts_list.html
{% extends 'base.html' %}
{% load main_filter %}
{% block content %}

<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'main:posts_create' %}" class="btn btn-primary">글쓰기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr class="text-center table-dark">
                <th>번호</th>
                <th style="width: 50%;">제목</th>
                <th>글쓴이</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% if posts_list %}
            {% for posts in posts_list %}
            <tr class="text-center">
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                <td>{{ posts_list.paginator.count|sub:posts_list.start_index|sub:forloop.counter0|add:1 }}</td>
                <td class="text-start">
                    <a href="{% url 'main:detail' posts.id %}">{{ posts.subject }}</a>
                    {% if posts.reply_set.count > 0 %}
                    <span class="text-danger small mx-2">{{ posts.reply_set.count }}</span>
                    {% endif %}
                </td>
                <td><a href="{% url 'common:userdetail' posts.author.profile.user_id %}">{{ posts.author.username }}</a></td>
                <td>{{ posts.create_date }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="4">일기가 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if posts_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ posts_list.previous_page_number }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in posts_list.paginator.page_range %}
        {% if page_number >= posts_list.number|add:-5 and posts_list.number|add:5 >= page_number %}
        {% if page_number == posts_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if posts_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ posts_list.next_page_number }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascripit:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
<form id="searchForm" method="get" action="{% url 'main:index' category %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

django/mydiary/templates/main/reply_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 댓글 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">댓글 내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}