django/mydiary/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    path('userdetail/<int:user_id>/', views.userdetail, name='userdetail'),
    path('userdetail/profile_modify/<int:user_id>/', views.profile_modify, name='profile_modify'),
    path('userdetail/profile_delete/<int:user_id>/', views.profile_delete, name='profile_delete'),
]


handler404 = 'common.views.page_not_found'

django/mydiary/main/urls.py
from django.urls import path
from .views import base_views, posts_views, reply_views


app_name = 'main'

urlpatterns = [
    path('<str:category>/', base_views.index, name='index'),
    path('detail/<int:posts_id>/', base_views.detail, name='detail'),
    
    path('posts/create/', posts_views.posts_create, name='posts_create'),
    path('posts/modify/<int:posts_id>/', posts_views.posts_modify, name='posts_modify'),
    path('posts/delete/<int:posts_id>/', posts_views.posts_delete, name='posts_delete'),
    path('posts/vote/<int:posts_id>/', posts_views.posts_vote, name='posts_vote'),

    path('reply/create/<int:posts_id>/', reply_views.reply_create, name='reply_create'),
    path('reply/modify/<int:reply_id>/', reply_views.reply_modify, name='reply_modify'),
    path('reply/delete/<int:reply_id>/', reply_views.reply_delete, name='reply_delete'),
    path('reply/vote/<int:reply_id>/', reply_views.reply_vote, name='reply_vote'),
]

django/mydiary/main/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from ..models import Posts
from django.db.models import Q, Count



def index(request, category=None):
    page = request.GET.get('page', '1') # 페이지를 읽어온다. 없을경우 1을 뱉는다 ?page =
    kw = request.GET.get('kw', '') # 검색어

    if category == 'freeboard':
        posts_list = Posts.objects.filter(category_id=1).order_by('-create_date')
    elif category == 'diary':
        posts_list = Posts.objects.filter(category_id=2).order_by('-create_date')
    elif category == 'QnA':
        posts_list = Posts.objects.filter(category_id=3).order_by('-create_date')
    else:
        posts_list = Posts.objects.order_by('-create_date')

    if kw:
        posts_list = posts_list.filter( # icontains 대소문자 구분없음, 있음은 contains
            Q(subject__icontains=kw) | # 제목 검색
            Q(content__icontains=kw) | # 내용 검색
            Q(reply__content__icontains=kw) | # 댓글 내용
            Q(reply__author__username__icontains=kw) | # 댓글 작성자
            Q(author__username__icontains=kw) # 일기 작성자
        ).distinct() # 중복제거
    paginator = Paginator(posts_list, 10) # 한페이지에 보여줄 페이지 갯수 10
    page_obj = paginator.get_page(page) # 페이지 오브젝트에 담아서 보여줌
    context = {'category': category, 'posts_list': page_obj, 'page': page, 'kw': kw}

    return render(request, 'main/posts_list.html', context)


def detail(request, posts_id):
    posts = get_object_or_404(Posts, pk=posts_id)

    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', 'first') # 정렬방법

    if kw == 'voter': # 추천순
        paginator = Paginator(posts.reply_set.all().annotate(num_votes=Count('voter')).order_by('-num_votes'), 10)
    elif kw == 'latest': # 최신순
        paginator = Paginator(posts.reply_set.all().order_by('-id'), 10)
    else: # 등록순
        paginator = Paginator(posts.reply_set.all(), 10)

    page_obj = paginator.get_page(page)

    context = {'posts': posts, 'reply_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'main/posts_detail.html', context)

django/mydiary/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>홈페이지</title>

    <!-- JQuery 임포트 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <!-- 네비게이션바 -->
    {% include "navbar.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->
</body>

</html>

django/mydiary/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

django/mydiary/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:index' 'all' %}">홈페이지</a>
        <a class="nav-link text-dark" href="{% url 'main:index' 'all' %}">전체글</a>
        <a class="nav-link text-dark" href="{% url 'main:index' 'freeboard' %}">자유게시판</a>
        <a class="nav-link text-dark" href="{% url 'main:index' 'diary' %}">일기장</a>
        <a class="nav-link text-dark" href="{% url 'main:index' 'QnA' %}">Q&A</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li>
                    <a class="nav-link" href="{% url 'common:userdetail' user.id %}">{{ user.username }}</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'common:logout' %}">(로그아웃)</a>
                </li>
                {% else %}
                <li>
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>