django/mydiary/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    path('userdetail/<int:user_id>/', views.userdetail, name='userdetail'),
    path('userdetail/profile_modify/<int:user_id>/', views.profile_modify, name='profile_modify'),
    path('userdetail/profile_delete/<int:user_id>/', views.profile_delete, name='profile_delete'),
]


handler404 = 'common.views.page_not_found'

django/mydiary/main/urls.py
from django.urls import path
from .views import base_views, posts_views, reply_views


app_name = 'main'

urlpatterns = [
    path('<str:category>/', base_views.index, name='index'),
    path('detail/<int:posts_id>/', base_views.detail, name='detail'),
    
    path('posts/create/', posts_views.posts_create, name='posts_create'),
    path('posts/modify/<int:posts_id>/', posts_views.posts_modify, name='posts_modify'),
    path('posts/delete/<int:posts_id>/', posts_views.posts_delete, name='posts_delete'),
    path('posts/vote/<int:posts_id>/', posts_views.posts_vote, name='posts_vote'),

    path('reply/create/<int:posts_id>/', reply_views.reply_create, name='reply_create'),
    path('reply/modify/<int:reply_id>/', reply_views.reply_modify, name='reply_modify'),
    path('reply/delete/<int:reply_id>/', reply_views.reply_delete, name='reply_delete'),
    path('reply/vote/<int:reply_id>/', reply_views.reply_vote, name='reply_vote'),
]

django/mydiary/common/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model): # 기본 유저모델에 간단하게 추가해서 사용
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    introduction = models.CharField(max_length=100, default="자기소개 입니다.")
    bloodtype = models.CharField(max_length=20, default="혈액형을 알려주세요.")

    def __str__(self):
        return self.user.username

django/mydiary/main/models.py
from django.db import models
from django.contrib.auth.models import User



class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    def __str__(self):
        return self.name


class Posts(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_posts')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_posts', null=True)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_posts')

    def __str__(self):
        return self.subject


class Reply(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_reply')
    posts = models.ForeignKey(Posts, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    # null=True : 데이터베이스에서 null을 허용, blanck=True : form_isvalid 에서 값이 없어도 검사를 통과를 허용
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_reply')

django/mydiary/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from common.models import Profile



class UserForm(UserCreationForm):
    email = forms.EmailField(label='이메일')
    class Meta:
        model = User  # 사용할 모델
        fields = ('username', 'email', 'password1', 'password2')  # UserForm에서 사용할 User 모델의 속성


class Profile_ModifyForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['introduction', 'bloodtype']
        labels = {
            'introduction': '자기소개',
            'bloodtype': '혈액형'
        }

django/mydiary/common/views.py
from multiprocessing import context
from django.shortcuts import render, redirect, get_object_or_404
from common.forms import Profile_ModifyForm, UserForm
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.decorators import login_required
from django.contrib import messages



def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            user = User.objects.get(username=form.cleaned_data.get('username'))
            Profile.objects.create(user_id=user.id)
            return redirect('common:login')
            # # 로그인 후 자동으로 로그인 되기를 원한다면
            # username = form.cleaned_data.get('username')
            # raw_password = form.cleaned_data.get('password1')
            # user = authenticate(username=username, password=raw_password)  # 사용자 인증
            # login(request, user)  # 로그인
            # return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})


def userdetail(request, user_id):
    userdetail = get_object_or_404(User, pk=user_id)
    posts_list = userdetail.author_posts.all().order_by('-create_date')
    reply_list = userdetail.author_reply.all()

    context = {'userdetail': userdetail, 'posts_list': posts_list, 'reply_list': reply_list}
    return render(request, 'common/userdetail.html', context)


@login_required(login_url='common:login')
def profile_modify(request, user_id):
    profile = get_object_or_404(Profile, user_id=user_id)
    if request.user != profile.user:
        messages.error(request, '권한이 없습니다.')
        return redirect('/')
    if request.method == 'POST':
        form = Profile_ModifyForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('common:userdetail', user_id=profile.user_id)
    else:
        form = Profile_ModifyForm(instance=profile)
    context = {'form': form}
    return render(request, 'common/profile_modify.html', context)


@login_required(login_url='common:login')
def profile_delete(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if request.user != user:
        messages.error(request, '권한이 없습니다.')
        return redirect('/')
    user.delete()
    return redirect('/')


def page_not_found(request, exception):
    return render(request, 'common/404.html', {})

django/mydiary/templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}"><!-- 로그인 후 주소창의 ?next= 뒤로 이동 -->
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

django/mydiary/templates/common/profile_modify.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="my-3 border-bottom pb-2 modify-profile-title">
        <h5 class="">{{ user.username }}</h5>
        <a href="javascript:void(0)" data-uri="{% url 'common:profile_delete' user.id %}" type="button"
            class="profile_delete btn btn-outline-danger">계정 삭제하기</a>
    </div>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% include "form_errors.html" %}
        <!-- 오류표시 End -->
        <!-- <div class="mb-3">
            <label for="subject" class="form-label">이메일</label>
            <input type="text" class="form-control" name="subject" id="subject"
                value="{{ form.subject.value|default_if_none:'' }}">
        </div> -->
        <div class="mb-3">
            <label for="introduction" class="form-label">자기소개</label>
            <textarea class="form-control" name="introduction" id="introduction"
                rows="3">{{ form.introduction.value|default_if_none:'' }}</textarea>
        </div>
        <div class="mb-3">
            <label for="bloodtype" class="form-label">혈액형</label>
            <select name="bloodtype" class="form-control">
                <option value="">---혈액형을 선택하세요---</option>
                <option value="A형">A형</option>
                <option value="B형">B형</option>
                <option value="O형">O형</option>
                <option value="AB형">AB형</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">수정하기</button>
    </form>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
    const profile_delete_elements = document.getElementsByClassName("profile_delete");
    Array.from(profile_delete_elements).forEach(function (element) {
        element.addEventListener('click', function () {
            if (confirm("삭제 시 복구가 불가능합니다. 정말로 삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });
</script>
{% endblock %}

django/mydiary/templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">회원가입</button>
    </form>
</div>
{% endblock %}

django/mydiary/templates/common/userdetail.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<h5 class="my-3 border-bottom pb-2">{{ userdetail.username }}</h2>
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">기본 정보</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">게시글</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">댓글</button>
  </li>
  {% if request.user == userdetail %}
  <li class="nav-item" role="presentation">
    <a href="{% url 'common:profile_modify' request.user.id %}" class="nav-link" aria-selected="false" type="button">프로필 수정</a>
  </li>
  {% endif %}
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
    <ul>
      <li>
        {{ userdetail.profile.introduction }}
      </li>
      <li>
        {{ userdetail.profile.bloodtype }}
      </li>
    </ul>
  </div>
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
    <table class="table">
      <thead>
          <tr class="text-center">
              <th>번호</th>
              <th style="width: 50%;">제목</th>
              <th>작성일시</th>
          </tr>
      </thead>
      <tbody>
          {% if posts_list %}
          {% for posts in posts_list %}
          <tr class="text-center">
              <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
              <td>{{ forloop.counter }}</td>
              <td class="text-start">
                  <a href="{% url 'main:detail' posts.id %}">{{ posts.subject }}</a>
                  {% if posts.reply_set.count > 0 %}
                  <span class="text-danger small mx-2">{{ posts.reply_set.count }}</span>
                  {% endif %}
              </td>
              <td>{{ posts.create_date }}</td>
          </tr>
          {% endfor %}
          {% else %}
          <tr>
              <td colspan="3">일기가 없습니다.</td>
          </tr>
          {% endif %}
      </tbody>
  </table>
  </div>
  <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
    <table class="table">
      <thead>
          <tr class="text-center">
              <th>번호</th>
              <th style="width: 50%;">댓글</th>
              <th>작성일시</th>
          </tr>
      </thead>
      <tbody>
          {% if reply_list %}
          {% for reply in reply_list %}
          <tr class="text-center">
              <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
              <td>{{ forloop.counter }}</td>
              <td class="text-start">
                  <a href="{% url 'main:detail' reply.posts.id %}">{{ reply.content }}</a>
              </td>
              <td>{{ reply.create_date }}</td>
          </tr>
          {% endfor %}
          {% else %}
          <tr>
              <td colspan="3">댓글이 없습니다.</td>
          </tr>
          {% endif %}
      </tbody>
  </table>
  </div>
</div>
</div>
{% endblock %}